apiVersion: v1
kind: Service
metadata:
  name: go-datetime-service
spec:
  selector:
    app: go-datetime-app
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30007
